version: '3.9'
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
    env_file: .env
    volumes:
      - .:/app

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:80"
    env_file: .env

